#!/bin/sh

# before running this script, edit date and version in
# Changelog, PackageInfo.g, etc/VERSION, etc/make_tar
# etc/changelog.html, doc/manual.tex

./make_tar

cp VERSION          ~/WWW/gap/CrystCat
cp changelog.html   ~/WWW/gap/CrystCat
mv *.tar.gz         ~/WWW/gap/CrystCat
cp ../PackageInfo.g ~/WWW/gap/CrystCat
tail +4 ../README.md > ~/WWW/gap/CrystCat/README.crystcat

cd ~/WWW/gap; ./get_html; chmod -R a+r *

