#!/bin/sh

PKGTAR=crystcat-1.1.10.tar

# remove old archive
rm -f $PKGTAR*

# update documentaion
(cd ../doc; ./make_doc;)

# make the package archive
mkdir -p crystcat/doc crystcat/lib crystcat/grp crystcat/htm crystcat/tst
cp -p ../*.g ../README ../Changelog ../GPL crystcat/
cp -p ../doc/manual.bbl ../doc/manual.six ../doc/manual.lab ../doc/manual.toc \
  ../doc/manual.mst ../doc/manual.pdf ../doc/*.tex ../doc/make_doc crystcat/doc/
cp -p ../lib/*.g[di] crystcat/lib/
cp -p ../grp/crystcat.grp crystcat/grp/
cp -p ../tst/*.tst ../tst/testall.g crystcat/tst/
cp -p ../htm/*.htm crystcat/htm/
chmod -R a+rX crystcat
tar cvf $PKGTAR crystcat
chmod a+r $PKGTAR
gzip $PKGTAR

# cleanup
rm -rf crystcat
