#!/bin/sh

PKGZOO=crystcat-1.1.5.zoo

# remove old archive
rm -f $PKGZOO

# update documentaion
(cd ../doc; ./make_doc; chmod a+r *; cd ../htm; chmod a+r *)

# goto <gaproot>/pkg
cd ../..

# make the package archive

# first the binary files
echo "!BINARY!" | zoo ach crystcat/etc/$PKGZOO crystcat/doc/manual.dvi
echo "!BINARY!" | zoo ach crystcat/etc/$PKGZOO crystcat/doc/manual.pdf

# then the text files
echo "!TEXT!" | zoo ach crystcat/etc/$PKGZOO crystcat/doc/manual.tex
echo "!TEXT!" | zoo ach crystcat/etc/$PKGZOO crystcat/doc/manual.bbl
echo "!TEXT!" | zoo ach crystcat/etc/$PKGZOO crystcat/doc/manual.six
echo "!TEXT!" | zoo ach crystcat/etc/$PKGZOO crystcat/doc/manual.lab
echo "!TEXT!" | zoo ach crystcat/etc/$PKGZOO crystcat/doc/manual.toc
echo "!TEXT!" | zoo ach crystcat/etc/$PKGZOO crystcat/doc/manual.mst
echo "!TEXT!" | zoo ach crystcat/etc/$PKGZOO crystcat/doc/manual.ps
echo "!TEXT!" | zoo ach crystcat/etc/$PKGZOO crystcat/doc/crystcat.tex
echo "!TEXT!" | zoo ach crystcat/etc/$PKGZOO crystcat/doc/make_doc
echo "!TEXT!" | zoo ach crystcat/etc/$PKGZOO crystcat/PackageInfo.g
echo "!TEXT!" | zoo ach crystcat/etc/$PKGZOO crystcat/init.g
echo "!TEXT!" | zoo ach crystcat/etc/$PKGZOO crystcat/read.g
echo "!TEXT!" | zoo ach crystcat/etc/$PKGZOO crystcat/README
echo "!TEXT!" | zoo ach crystcat/etc/$PKGZOO crystcat/Changelog
echo "!TEXT!" | zoo ach crystcat/etc/$PKGZOO crystcat/GPL
echo "!TEXT!" | zoo ach crystcat/etc/$PKGZOO crystcat/grp/crystcat.grp
for file in crystcat/lib/*.g[di] ; do
  echo "!TEXT!" | zoo ach crystcat/etc/$PKGZOO $file
done
for file in crystcat/htm/*.htm ; do
  echo "!TEXT!" | zoo ach crystcat/etc/$PKGZOO $file
done

# check the results
cd crystcat/etc
chmod a+r $PKGZOO
zoo -list $PKGZOO
